create table discharge_reminders (
  id bigint generated by default as identity primary key,
  department_id bigint not null references departments(id),
  admission_id bigint not null references admissions(id) on delete cascade,
  expected_discharge_date date not null,
  window_days integer not null check (window_days between 1 and 365),
  status varchar(24) not null check (status in ('PENDING', 'SENDING', 'ACCEPTED', 'FAILED', 'NO_RECIPIENT', 'CANCELLED')),
  recipient_count integer not null default 0 check (recipient_count >= 0),
  attempt_count integer not null default 0 check (attempt_count >= 0),
  provider_message_id varchar(128),
  error_code varchar(64),
  last_attempt_at timestamptz,
  next_attempt_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (admission_id, expected_discharge_date, window_days)
);

create index discharge_reminders_queue on discharge_reminders(status, next_attempt_at, last_attempt_at);
create index discharge_reminders_department on discharge_reminders(department_id, created_at desc);
create index active_expected_discharges on admissions(department_id, expected_discharge_date)
  where status = 'ACTIVE' and expected_discharge_date is not null;
