create table bed_holds (
  id bigint generated by default as identity primary key,
  version bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  department_id bigint not null references departments(id),
  room_id bigint not null references rooms(id),
  bed_count integer not null check (bed_count between 1 and 100),
  reason varchar(500) not null,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  created_by bigint not null references app_users(id),
  cancelled_at timestamptz,
  cancelled_by bigint references app_users(id),
  check (ends_at > starts_at)
);

create index bed_holds_room_window
  on bed_holds(room_id, starts_at, ends_at)
  where cancelled_at is null;
