-- Server-side notification inbox (#303), per-user read state (#304), deduplicated
-- capacity alerts (#317), acknowledgement escalation (#310) and per-department policy (#320).

create table notification_policies (
  department_id bigint primary key references departments(id) on delete cascade,
  version bigint not null default 1,
  capacity_alerts_enabled boolean not null default true,
  activity_notices_enabled boolean not null default true,
  warning_percent integer not null check (warning_percent between 1 and 99),
  critical_percent integer not null check (critical_percent between 2 and 100),
  escalation_enabled boolean not null default true,
  escalation_min_severity varchar(20) not null default 'CRITICAL'
    check (escalation_min_severity in ('WARNING', 'CRITICAL')),
  acknowledgement_minutes integer not null default 30 check (acknowledgement_minutes between 5 and 1440),
  escalation_role varchar(30) not null default 'ADMIN' check (escalation_role in ('ADMIN', 'MEDICAL_STAFF')),
  retention_days integer not null default 14 check (retention_days between 1 and 90),
  updated_at timestamptz not null default now(),
  updated_by bigint references app_users(id) on delete set null,
  check (warning_percent < critical_percent)
);

create table notifications (
  id bigint generated by default as identity primary key,
  version bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  department_id bigint not null references departments(id) on delete cascade,
  -- null: a department alert visible to every member; set: a personal notice for one account.
  recipient_user_id bigint references app_users(id) on delete cascade,
  category varchar(30) not null check (category in ('CAPACITY', 'ACTIVITY')),
  type varchar(60) not null,
  severity varchar(20) not null check (severity in ('INFO', 'WARNING', 'CRITICAL')),
  dedupe_key varchar(190),
  source_type varchar(40),
  source_id bigint,
  title varchar(200) not null,
  detail varchar(500),
  status varchar(20) not null check (status in ('OPEN', 'RESOLVED', 'INFO')),
  first_seen_at timestamptz not null,
  last_seen_at timestamptz not null,
  resolved_at timestamptz,
  acknowledgement_due_at timestamptz,
  acknowledged_at timestamptz,
  acknowledged_by bigint references app_users(id) on delete set null,
  escalated_at timestamptz,
  escalated_to_role varchar(30) check (escalated_to_role in ('ADMIN', 'MEDICAL_STAFF')),
  expires_at timestamptz,
  check (category <> 'ACTIVITY' or recipient_user_id is not null),
  check (status <> 'OPEN' or dedupe_key is not null)
);

-- One open notice per underlying condition. Resolved history keeps its own rows.
create unique index notifications_open_condition
  on notifications (department_id, dedupe_key)
  where status = 'OPEN';
create index notifications_inbox on notifications (department_id, recipient_user_id, last_seen_at desc);
create index notifications_escalation_due on notifications (department_id, acknowledgement_due_at)
  where status = 'OPEN' and acknowledged_at is null and escalated_at is null;
create index notifications_expiry on notifications (expires_at) where expires_at is not null;

create table notification_reads (
  notification_id bigint not null references notifications(id) on delete cascade,
  user_id bigint not null references app_users(id) on delete cascade,
  read_at timestamptz not null default now(),
  primary key (notification_id, user_id)
);
create index notification_reads_user on notification_reads (user_id);
