create table care_workflow_templates (
  id bigint generated by default as identity primary key,
  department_id bigint not null references departments(id),
  name varchar(160) not null,
  description varchar(1000),
  draft_definition text not null,
  version bigint not null default 0,
  published_version integer,
  created_by bigint not null references app_users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(department_id, name)
);

create table care_workflow_versions (
  id bigint generated by default as identity primary key,
  department_id bigint not null references departments(id),
  template_id bigint not null references care_workflow_templates(id),
  version_number integer not null,
  definition text not null,
  published_by bigint not null references app_users(id),
  published_at timestamptz not null default now(),
  unique(template_id, version_number),
  unique(department_id, id)
);

create table care_workflow_runs (
  id bigint generated by default as identity primary key,
  department_id bigint not null references departments(id),
  template_id bigint not null references care_workflow_templates(id),
  workflow_version_id bigint not null,
  patient_id bigint not null references patients(id),
  admission_id bigint references admissions(id),
  trigger_type varchar(20) not null check(trigger_type in ('MANUAL','ADMISSION','DISCHARGE')),
  trigger_source_id varchar(120) not null,
  status varchar(20) not null default 'ACTIVE' check(status in ('ACTIVE','CANCELLED','COMPLETED')),
  version bigint not null default 0,
  source_reference varchar(200),
  patient_summary varchar(2000),
  reviewed_by bigint not null references app_users(id),
  reviewed_at timestamptz not null default now(),
  launched_by bigint not null references app_users(id),
  launched_at timestamptz not null default now(),
  cancelled_by bigint references app_users(id),
  cancelled_at timestamptz,
  unique(department_id, template_id, workflow_version_id, trigger_type, trigger_source_id),
  foreign key(department_id, workflow_version_id) references care_workflow_versions(department_id, id)
);

create table care_tasks (
  id bigint generated by default as identity primary key,
  department_id bigint not null references departments(id),
  workflow_run_id bigint not null references care_workflow_runs(id),
  template_task_key varchar(80) not null,
  title varchar(200) not null,
  description varchar(2000),
  owner_role varchar(30) not null check(owner_role in ('ADMIN','MEDICAL_STAFF','DOCTOR')),
  assigned_user_id bigint references app_users(id),
  due_at timestamptz,
  status varchar(20) not null default 'OPEN' check(status in ('OPEN','IN_PROGRESS','COMPLETED','CANCELLED')),
  dependency_state varchar(20) not null default 'READY' check(dependency_state in ('READY','BLOCKED')),
  version bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(workflow_run_id, template_task_key),
  unique(department_id, id)
);

create table care_task_dependencies (
  department_id bigint not null,
  task_id bigint not null,
  depends_on_task_id bigint not null,
  primary key(task_id, depends_on_task_id),
  check(task_id <> depends_on_task_id),
  foreign key(department_id, task_id) references care_tasks(department_id, id),
  foreign key(department_id, depends_on_task_id) references care_tasks(department_id, id)
);

create index care_workflow_templates_department on care_workflow_templates(department_id, updated_at desc);
create index care_workflow_runs_patient on care_workflow_runs(department_id, patient_id, launched_at desc);
create index care_tasks_assignee_due on care_tasks(department_id, assigned_user_id, due_at) where status in ('OPEN','IN_PROGRESS');
create index care_task_dependencies_source on care_task_dependencies(department_id, depends_on_task_id);
