create table patients (id bigint generated by default as identity primary key, version bigint not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
patient_identifier varchar(64) not null unique, first_name varchar(100) not null, last_name varchar(100) not null, date_of_birth date not null, address varchar(500), phone_number varchar(40));
create table doctors (id bigint generated by default as identity primary key, version bigint not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
doctor_identifier varchar(64) not null unique, first_name varchar(100) not null, last_name varchar(100) not null, specialty varchar(100) not null, active boolean not null default true);
create table rooms (id bigint generated by default as identity primary key, version bigint not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
room_number varchar(30) not null unique, bed_count integer not null check(bed_count between 1 and 100), active boolean not null default true);
create table medical_procedures (id bigint generated by default as identity primary key, version bigint not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
procedure_code varchar(64) not null unique, procedure_name varchar(150) not null, current_cost numeric(12,2) not null check(current_cost>=0), active boolean not null default true);
create table app_users (id bigint generated by default as identity primary key, version bigint not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
username varchar(64) not null unique, password_hash varchar(255) not null, role varchar(30) not null check(role in ('ADMIN','MEDICAL_STAFF','DOCTOR')), enabled boolean not null default true, doctor_id bigint references doctors(id), last_login_at timestamptz, check(role <> 'DOCTOR' or doctor_id is not null));
create table admissions (id bigint generated by default as identity primary key, version bigint not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
admission_number varchar(64) not null unique, patient_id bigint not null references patients(id), attending_doctor_id bigint not null references doctors(id), admission_date_time timestamptz not null, discharge_date_time timestamptz, status varchar(30) not null check(status in ('ACTIVE','DISCHARGED','CANCELLED')), created_by bigint not null references app_users(id), check(discharge_date_time is null or discharge_date_time>=admission_date_time));
create table room_assignments (id bigint generated by default as identity primary key, version bigint not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
admission_id bigint not null references admissions(id), room_id bigint not null references rooms(id), assigned_at timestamptz not null, released_at timestamptz, reason varchar(500), created_by bigint not null references app_users(id), check(released_at is null or released_at>=assigned_at));
create table performed_procedures (id bigint generated by default as identity primary key, version bigint not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
admission_id bigint not null references admissions(id), medical_procedure_id bigint not null references medical_procedures(id), performed_by_doctor_id bigint not null references doctors(id), performed_at timestamptz not null, note varchar(2000), price_at_execution numeric(12,2) not null check(price_at_execution>=0));
create table audit_events (id bigint generated by default as identity primary key, version bigint not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
user_id bigint references app_users(id), event_type varchar(80) not null, entity_type varchar(80) not null, entity_id bigint, source varchar(30) not null, timestamp timestamptz not null, metadata varchar(500));
create table ai_interactions (id bigint generated by default as identity primary key, version bigint not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
user_id bigint not null references app_users(id), session_id varchar(64) not null, request_type varchar(80), model_identifier varchar(150), tool_names varchar(150), status varchar(50), started_at timestamptz not null, completed_at timestamptz, latency_ms bigint);
create table ai_pending_actions (id bigint generated by default as identity primary key, version bigint not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
user_id bigint not null references app_users(id), action_type varchar(40) not null, payload text not null, status varchar(30) not null, expires_at timestamptz not null, confirmed_at timestamptz);
create table ai_sessions (id bigint generated by default as identity primary key, version bigint not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
session_key varchar(64) not null unique, user_id bigint not null references app_users(id), selected_patient_id bigint references patients(id));
create unique index one_active_admission on admissions(patient_id) where status='ACTIVE';
create unique index one_active_room on room_assignments(admission_id) where released_at is null;
create index occupancy on room_assignments(room_id) where released_at is null;
create index doctor_admissions on admissions(attending_doctor_id, patient_id);
create index procedure_period on performed_procedures(performed_at);
create index interaction_owner on ai_interactions(user_id, session_id);
create table workflow_lock (id bigint primary key);
insert into workflow_lock(id) values (1);
