-- Owner decisions from periodic access reviews. History is kept; the latest row per member is
-- the current outcome. Recording a decision never changes access by itself.
create table access_reviews (
  id bigint generated by default as identity primary key,
  hospital_id bigint not null references hospitals(id) on delete cascade,
  user_id bigint not null references app_users(id) on delete cascade,
  outcome varchar(20) not null check (outcome in ('KEEP', 'CHANGE', 'REVOKE')),
  note varchar(300),
  reviewed_by bigint not null references app_users(id) on delete cascade,
  reviewed_at timestamptz not null default now()
);
create index access_reviews_latest on access_reviews(hospital_id, user_id, reviewed_at desc, id desc);
