create table patient_consents (
  id bigint generated by default as identity primary key,
  department_id bigint not null references departments(id),
  patient_id bigint not null references patients(id),
  consent_type varchar(40) not null check(consent_type in ('PORTAL_FOLLOW_UP_SUMMARY','PORTAL_ACCESS','CARE_COMMUNICATION')),
  consent_version varchar(40) not null,
  recorded_at timestamptz not null default now(),
  recorded_by bigint not null references app_users(id),
  withdrawn_at timestamptz,
  withdrawn_by bigint references app_users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index patient_consents_current on patient_consents(department_id, patient_id, consent_type, recorded_at desc);
