-- Administrator security review queue (#352). Repeated signals of the same kind are grouped into
-- one open row per department and dedupe key; once resolved or dismissed, new signals open a new row.
create table security_events (
  id bigint generated by default as identity primary key,
  department_id bigint not null references departments(id) on delete cascade,
  category varchar(30) not null check (category in ('FAILED_LOGIN', 'ACCESS_DENIED', 'ROLE_CHANGE', 'JOIN_CODE')),
  type varchar(60) not null,
  severity varchar(20) not null check (severity in ('INFO', 'WARNING', 'CRITICAL')),
  escalates boolean not null default false,
  subject_user_id bigint references app_users(id) on delete set null,
  subject varchar(120),
  detail varchar(300),
  occurrences integer not null default 1,
  dedupe_key varchar(190) not null,
  first_seen_at timestamptz not null,
  last_seen_at timestamptz not null,
  status varchar(20) not null default 'OPEN' check (status in ('OPEN', 'INVESTIGATING', 'RESOLVED', 'DISMISSED')),
  acknowledged_by bigint references app_users(id) on delete set null,
  acknowledged_at timestamptz,
  status_note varchar(300),
  status_changed_by bigint references app_users(id) on delete set null,
  status_changed_at timestamptz
);
create unique index security_events_open_group
  on security_events (department_id, dedupe_key)
  where status in ('OPEN', 'INVESTIGATING');
create index security_events_inbox on security_events (department_id, status, last_seen_at desc);
