-- Hospital ownership changes need the new owner's acceptance (#362). A transfer is requested by a
-- current owner, optionally with the requester stepping down, and expires if not accepted.
create table ownership_transfers (
  id bigint generated by default as identity primary key,
  hospital_id bigint not null references hospitals(id) on delete cascade,
  from_user_id bigint not null references app_users(id) on delete cascade,
  to_user_id bigint not null references app_users(id) on delete cascade,
  step_down boolean not null default false,
  reason varchar(300),
  status varchar(20) not null default 'PENDING'
    check (status in ('PENDING', 'ACCEPTED', 'DECLINED', 'CANCELLED')),
  requested_at timestamptz not null default now(),
  expires_at timestamptz not null,
  resolved_at timestamptz
);
create unique index ownership_transfers_one_pending
  on ownership_transfers (hospital_id, to_user_id) where status = 'PENDING';
create index ownership_transfers_incoming on ownership_transfers (to_user_id, status);
