-- Client-supplied Idempotency-Key values for retried mutations (#387). A key belongs to one account;
-- its first request is replayed for retries until the row expires.
create table idempotency_keys (
  id bigint generated by default as identity primary key,
  user_id bigint not null references app_users(id) on delete cascade,
  idempotency_key varchar(128) not null,
  request_hash varchar(64) not null,
  status varchar(20) not null check (status in ('IN_PROGRESS', 'COMPLETED')),
  response_status integer,
  response_content_type varchar(120),
  response_body text,
  created_at timestamptz not null default now(),
  unique (user_id, idempotency_key)
);
create index idempotency_keys_created on idempotency_keys (created_at);
