-- Personal, revocable calendar feeds of expected discharge dates (#392). Only a hash of the feed
-- token is stored; the token itself is shown once when the feed is created.
create table calendar_feeds (
  id bigint generated by default as identity primary key,
  user_id bigint not null references app_users(id) on delete cascade,
  department_id bigint not null references departments(id) on delete cascade,
  token_hash varchar(64) not null unique,
  created_at timestamptz not null default now(),
  last_used_at timestamptz,
  revoked_at timestamptz
);
create unique index calendar_feeds_one_active
  on calendar_feeds (user_id, department_id) where revoked_at is null;
