create table room_beds (
  id bigint generated by default as identity primary key,
  version bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  department_id bigint not null references departments(id),
  room_id bigint not null references rooms(id) on delete cascade,
  identifier varchar(64) not null,
  constraint room_beds_room_identifier unique (room_id, identifier),
  constraint room_beds_room_id_id_unique unique (room_id, id)
);

insert into room_beds (department_id, room_id, identifier)
select r.department_id, r.id, bed_number::text
from rooms r
cross join lateral generate_series(1, r.bed_count) as beds(bed_number);

create trigger reject_archived_department_write before insert or update or delete on room_beds
  for each row execute function reject_archived_department_write();

alter table room_assignments add column bed_id bigint;
alter table room_assignments add column bed_identifier varchar(64);
alter table room_assignments add constraint room_assignments_bed_room_fk
  foreign key (room_id, bed_id) references room_beds(room_id, id);
create unique index one_active_assignment_per_bed
  on room_assignments(bed_id) where released_at is null and bed_id is not null;
create index room_beds_room on room_beds(room_id, identifier);
