-- Namespaced identifiers that other systems use for local records (#402). Within a department an
-- external identifier points at one record, and a record has at most one identifier per namespace.
create table external_identifiers (
  id bigint generated by default as identity primary key,
  department_id bigint not null references departments(id) on delete cascade,
  entity_type varchar(30) not null
    check (entity_type in ('PATIENT', 'ADMISSION', 'DOCTOR', 'ROOM', 'PROCEDURE')),
  entity_id bigint not null,
  namespace varchar(100) not null,
  value varchar(200) not null,
  source varchar(100),
  created_by bigint references app_users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (department_id, entity_type, namespace, value),
  unique (department_id, entity_type, entity_id, namespace)
);
create index external_identifiers_entity on external_identifiers (department_id, entity_type, entity_id);
