-- Patient-submitted demographic correction requests. A patient proposes a change to
-- their own contact details; staff review and apply it. The patient's record is never
-- edited directly from the portal, so a request carries its own before/after trail.
create table patient_correction_requests (
  id bigint generated by default as identity primary key,
  department_id bigint not null references departments(id),
  patient_id bigint not null references patients(id),
  requested_by bigint not null references app_users(id),
  field_name varchar(40) not null check(field_name in ('ADDRESS','PHONE_NUMBER','FIRST_NAME','LAST_NAME')),
  previous_value varchar(500),
  requested_value varchar(500) not null,
  reason varchar(500),
  status varchar(20) not null default 'PENDING' check(status in ('PENDING','APPROVED','REJECTED')),
  reviewed_by bigint references app_users(id),
  reviewed_at timestamptz,
  review_note varchar(500),
  patient_version bigint not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index patient_correction_requests_pending
  on patient_correction_requests(department_id, status, created_at desc);
create index patient_correction_requests_patient
  on patient_correction_requests(department_id, patient_id, created_at desc);
-- One open request per field, so a patient cannot pile up duplicates for the same edit.
create unique index patient_correction_requests_one_open
  on patient_correction_requests(department_id, patient_id, field_name)
  where status = 'PENDING';
