-- Administrator-reviewed linking of a self-registered portal account to the real
-- patient record. Registration deliberately creates a SELF-* patient rather than
-- guessing an existing identity, so this is the reviewed path that repairs it.
-- A linked account is then detached from its placeholder so the placeholder can be
-- retired, and app_users.patient_id stays unique so one account links one patient.
create table patient_account_links (
  id bigint generated by default as identity primary key,
  department_id bigint not null references departments(id),
  user_id bigint not null references app_users(id),
  placeholder_patient_id bigint not null references patients(id),
  target_patient_id bigint not null references patients(id),
  evidence varchar(500) not null,
  status varchar(20) not null default 'PENDING' check(status in ('PENDING','LINKED','REJECTED')),
  requested_by bigint references app_users(id),
  reviewed_by bigint references app_users(id),
  reviewed_at timestamptz,
  review_note varchar(500),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- The placeholder and the target must be different records, or "linking" would
  -- be a no-op that hides an unresolved duplicate.
  check (placeholder_patient_id <> target_patient_id)
);

create unique index patient_account_links_one_pending
  on patient_account_links(user_id) where status = 'PENDING';
create unique index patient_account_links_one_linked
  on patient_account_links(user_id) where status = 'LINKED';
create index patient_account_links_department
  on patient_account_links(department_id, status, created_at desc);
