-- Previewed bulk import for initial setup (#161). An uploaded file is parsed and
-- validated into a staging batch that the administrator reviews, then commits
-- explicitly. Nothing is written to the operational tables until that commit, so a
-- preview can never half-apply. The batch retains the source rows and the per-row
-- verdict so the reviewer and the audit trail can see exactly what was decided.
create table csv_import_batches (
  id bigint generated by default as identity primary key,
  department_id bigint not null references departments(id),
  entity_type varchar(20) not null check(entity_type in ('PATIENT','DOCTOR','ROOM','PROCEDURE')),
  file_name varchar(200) not null,
  status varchar(20) not null default 'PREVIEWED'
    check(status in ('PREVIEWED','COMMITTED','DISCARDED')),
  duplicate_policy varchar(20) not null default 'SKIP'
    check(duplicate_policy in ('SKIP','REJECT')),
  total_rows int not null,
  created_by bigint not null references app_users(id),
  committed_by bigint references app_users(id),
  committed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table csv_import_rows (
  id bigint generated by default as identity primary key,
  batch_id bigint not null references csv_import_batches(id) on delete cascade,
  row_number int not null,
  raw_row text not null,
  parsed_value text,
  status varchar(20) not null check(status in ('READY','SKIPPED_DUPLICATE','INVALID')),
  problems text,
  created_record_id bigint,
  unique (batch_id, row_number)
);

create index csv_import_batches_department
  on csv_import_batches(department_id, created_at desc);
-- A batch is committed at most once, so a double-clicked commit cannot import twice.
create unique index csv_import_batches_one_commit
  on csv_import_batches(id) where status = 'COMMITTED';
