create table doctor_appointments (
  id bigint generated by default as identity primary key,
  version bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  department_id bigint not null references departments(id),
  doctor_id bigint not null references doctors(id),
  attendee_name varchar(120) not null check (length(trim(attendee_name)) > 0),
  contact varchar(120) not null default '',
  notes varchar(500) not null default '',
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  created_by bigint not null references app_users(id),
  cancelled_at timestamptz,
  cancelled_by bigint references app_users(id),
  check (ends_at > starts_at),
  check (ends_at - starts_at between interval '5 minutes' and interval '4 hours'),
  check ((cancelled_at is null) = (cancelled_by is null))
);

create index doctor_appointments_schedule
  on doctor_appointments(department_id, doctor_id, starts_at, ends_at)
  where cancelled_at is null;
create index doctor_appointments_directory
  on doctor_appointments(department_id, starts_at, id);
