create table hospitals (
  id bigint generated by default as identity primary key,
  name varchar(120) not null,
  join_code varchar(32) not null unique
);
create table departments (
  id bigint generated by default as identity primary key,
  hospital_id bigint not null references hospitals(id),
  name varchar(120) not null,
  join_code varchar(32) not null unique,
  unique (hospital_id, name)
);
create table hospital_memberships (
  hospital_id bigint not null references hospitals(id),
  user_id bigint not null references app_users(id) on delete cascade,
  owner boolean not null default false,
  primary key (hospital_id, user_id)
);
create table department_memberships (
  department_id bigint not null references departments(id),
  user_id bigint not null references app_users(id) on delete cascade,
  role varchar(30) not null check (role in ('ADMIN','MEDICAL_STAFF','DOCTOR')),
  doctor_id bigint references doctors(id),
  primary key (department_id, user_id),
  check (role <> 'DOCTOR' or doctor_id is not null)
);
insert into hospitals(name, join_code) values ('Medcore Hospital', upper(replace(gen_random_uuid()::text, '-', '')));
insert into departments(hospital_id, name, join_code) values (1, 'General medicine', upper(replace(gen_random_uuid()::text, '-', '')));
insert into hospital_memberships select 1, id, role = 'ADMIN' from app_users where role <> 'PATIENT';
insert into department_memberships select 1, id, role, doctor_id from app_users where role <> 'PATIENT';

alter table patients add column department_id bigint not null default 1 references departments(id);
alter table doctors add column department_id bigint not null default 1 references departments(id);
alter table rooms add column department_id bigint not null default 1 references departments(id);
alter table medical_procedures add column department_id bigint not null default 1 references departments(id);
alter table admissions add column department_id bigint not null default 1 references departments(id);
alter table room_assignments add column department_id bigint not null default 1 references departments(id);
alter table performed_procedures add column department_id bigint not null default 1 references departments(id);
alter table audit_events add column department_id bigint not null default 1 references departments(id);
alter table ai_sessions add column department_id bigint not null default 1 references departments(id);
alter table ai_pending_actions add column department_id bigint not null default 1 references departments(id);
alter table ai_interactions add column department_id bigint not null default 1 references departments(id);

alter table patients drop constraint patients_patient_identifier_key;
alter table patients add unique (department_id, patient_identifier);
alter table doctors drop constraint doctors_doctor_identifier_key;
alter table doctors add unique (department_id, doctor_identifier);
alter table rooms drop constraint rooms_room_number_key;
alter table rooms add unique (department_id, room_number);
alter table medical_procedures drop constraint medical_procedures_procedure_code_key;
alter table medical_procedures add unique (department_id, procedure_code);
create index patients_department on patients(department_id);
create index admissions_department on admissions(department_id);
create index audit_department on audit_events(department_id);
